src/Entity/Agents.php
<?php

namespace App\Entity;


use App\Repository\AgentsRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=AgentsRepository::class)
 */

class Agents
{
    public function __toString()
    {
        return $this->prenom.' '.$this->nom.' Lieu de naissance: '.$this->nationalite.' Code Agent: '.$this->code_agent.' Spécialité : '.$this->specialite;

    }
    


    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $code_agent;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $specialite;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nationalite;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_naissance;

    /**
     * @ORM\ManyToOne(targetEntity=Missions::class, inversedBy="agent")
     */
    private $missions;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCodeAgent(): ?int
    {
        return $this->code_agent;
    }

    public function setCodeAgent(int $code_agent): self
    {
        $this->code_agent = $code_agent;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getSpecialite(): ?string
    {
        return $this->specialite;
    }

    public function setSpecialite(string $specialite): self
    {
        $this->specialite = $specialite;

        return $this;
    }

    public function getNationalite(): ?string
    {
        return $this->nationalite;
    }

    public function setNationalite(string $nationalite): self
    {
        $this->nationalite = $nationalite;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(\DateTimeInterface $date_naissance): self
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    public function getMissions(): ?Missions
    {
        return $this->missions;
    }

    public function setMissions(?Missions $missions): self
    {
        $this->missions = $missions;

        return $this;
    }


}

src/Entity/Cibles.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\CiblesRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CiblesRepository::class)
 */

class Cibles
{
    public function __toString()
    {

        return $this->nom_code.' Nom de Code: '.$this->prenom.' '.$this->nom.' Lieu de Naissance: '.$this->nationalite;

    }


    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_code;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nationalite;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_naissance;

    /**
     * @ORM\ManyToOne(targetEntity=Missions::class, inversedBy="cible")
     * @ORM\JoinColumn(nullable=true)
     */
    private $missions;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomCode(): ?string
    {
        return $this->nom_code;
    }

    public function setNomCode(string $nom_code): self
    {
        $this->nom_code = $nom_code;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getNationalite(): ?string
    {
        return $this->nationalite;
    }

    public function setNationalite(string $nationalite): self
    {
        $this->nationalite = $nationalite;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(\DateTimeInterface $date_naissance): self
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    public function getMissions(): ?Missions
    {
        return $this->missions;
    }

    public function setMissions(?Missions $missions): self
    {
        $this->missions = $missions;

        return $this;
    }
}

src/Entity/Missions.php
<?php

namespace App\Entity;


use App\Repository\MissionsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;


/**
 * @ORM\Entity(repositoryClass=MissionsRepository::class)
 *
 */
class Missions
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_code;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $pays;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_debut;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_fin;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $statut;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $specialite;


    /**
     * @ORM\OneToMany(targetEntity=Agents::class, mappedBy="missions", cascade={"persist"})
     */
    private $agent;

    /**
     * @ORM\OneToMany(targetEntity=Planques::class, mappedBy="missions")
     */
    private $planque;

    /**
     * @ORM\OneToMany(targetEntity=Contacts::class, mappedBy="missions")
     */
    private $contact;

    /**
     * @ORM\OneToMany(targetEntity=Cibles::class, mappedBy="missions")
     */
    private $cible;

    public function __construct()
    {
        $this->agent = new ArrayCollection();
        $this->planque = new ArrayCollection();
        $this->contact = new ArrayCollection();
        $this->cible = new ArrayCollection();
    }

    const TYPE = [
        'Infiltration' => 'Infiltration',
        'Assassinat' =>'Assassinat',
        'Diplomatie'=> 'Diplomatie',
        'Protection' =>'Protection'
    ];

    const SPEC = [
        'Explosifs' =>'Explosifs',
        'Relations humaines'=> 'Relations humaines',
        'Poison' => 'Poison',
        'Couteau' => 'Couteau',
        'Armes lourdes' => 'Armes lourdes',
        'Art de la discretion' => 'Art de la discretion'
    ];

    const STATUT = [
        'En préparation' => 'En préparation',
        'En cours'=> 'En cours',
        'Terminé' => 'Terminé'
    ];

    const PAYS = [
        'Japon' =>'Japon',
        'France' => 'France',
        'Angleterre' => 'Angleterre',
        'Ireland' => 'Ireland',
        'United States of America' => 'United States of America',
        'Russie' => 'Russie',
        'Pologne'=> 'Pologne',
        'Pays-Bas'=>'Pays-bas',
        'Chine'=>'Chine',
        'Mongolie'=>'Mongolie'
    ];

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomCode(): ?string
    {
        return $this->nom_code;
    }

    public function setNomCode(string $nom_code): self
    {
        $this->nom_code = $nom_code;

        return $this;
    }

    public function getPays(): ?string
    {
        return $this->pays;
    }

    public function setPays(string $pays): self
    {
        $this->pays = $pays;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(string $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    public function getSpecialite(): ?string
    {
        return $this->specialite;
    }

    public function setSpecialite(string $specialite): self
    {
        $this->specialite = $specialite;

        return $this;
    }

    /**
     * @return Collection|Agents[]
     */
    public function getAgent(): Collection
    {
        return $this->agent;
    }

    public function addAgent(Agents $agent): self
    {
        if (!$this->agent->contains($agent)) {
            $this->agent[] = $agent;
            $agent->setMissions($this);
        }

        return $this;
    }

    public function removeAgent(Agents $agent): self
    {
        if ($this->agent->removeElement($agent)) {
            // set the owning side to null (unless already changed)
            if ($agent->getMissions() === $this) {
                $agent->setMissions(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Planques[]
     */
    public function getPlanque(): Collection
    {
        return $this->planque;
    }

    public function addPlanque(Planques $planque): self
    {
        if (!$this->planque->contains($planque)) {
            $this->planque[] = $planque;
            $planque->setMissions($this);
        }

        return $this;
    }

    public function removePlanque(Planques $planque): self
    {
        if ($this->planque->removeElement($planque)) {
            // set the owning side to null (unless already changed)
            if ($planque->getMissions() === $this) {
                $planque->setMissions(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Contacts[]
     */
    public function getContact(): Collection
    {
        return $this->contact;
    }

    public function addContact(Contacts $contact): self
    {
        if (!$this->contact->contains($contact)) {
            $this->contact[] = $contact;
            $contact->setMissions($this);
        }

        return $this;
    }

    public function removeContact(Contacts $contact): self
    {
        if ($this->contact->removeElement($contact)) {
            // set the owning side to null (unless already changed)
            if ($contact->getMissions() === $this) {
                $contact->setMissions(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Cibles[]
     */
    public function getCible(): Collection
    {
        return $this->cible;
    }

    public function addCible(Cibles $cible): self
    {
        if (!$this->cible->contains($cible)) {
            $this->cible[] = $cible;
            $cible->setMissions($this);
        }

        return $this;
    }

    public function removeCible(Cibles $cible): self
    {
        if ($this->cible->removeElement($cible)) {
            // set the owning side to null (unless already changed)
            if ($cible->getMissions() === $this) {
                $cible->setMissions(null);
            }
        }

        return $this;
    }
    /**
     * @Assert\Callback()
     */
    public function validate(ExecutionContextInterface $context)
    {
        foreach ($this->getAgent() as $agent) {
            foreach ($this->getCible() as $cible){
                foreach ($this->getContact() as $contact){
                    foreach ($this->getPlanque() as  $planque){
                        if ($planque->getPays() != $this->pays){
                            $context->buildViolation('La planque doit être dans le même pays que la mission')
                                ->atPath('contact')
                                ->addViolation();
                        }
                    }
                    if ($contact->getNationalite() != $this->pays){
                        $context->buildViolation('le contact doit être du même pays que celui de la mission')
                            ->atPath('contact')
                            ->addViolation();
                    }
                }
                if ($cible->getNationalite() == $agent->getNationalite()){
                    $context->buildViolation('l\'Agent ne doit pas avoir la même nationalité que la cible')
                        ->atPath('cible')
                        ->addViolation();
                }
                if ($agent->getSpecialite() != $this->specialite ){
                    $context->buildViolation('l\'Agent doit avoir la même spécialité que la mission')
                        ->atPath('agent')
                        ->addViolation();
                }
            }

        }
    }




}

src/Entity/Planques.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\PlanquesRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=PlanquesRepository::class)
 */

class Planques
{

    public function __toString()
    {
        return ' Code: '.$this->code_planque.' - '.$this->type.' Adresse : '.$this->adresse.' Pays: '.$this->pays;

    }
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\NotBlank (message="Ce champs ne peut être vide")
     * @Assert\Type(type="integer", message="Ce champs doit être une valeur numérique")
     * @ORM\Column(type="integer")
     */
    private $code_planque;

    /**
     * @Assert\NotBlank (message="Ce champs ne peut être vide")
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @Assert\NotBlank (message="Ce champs ne peut être vide")
     * @ORM\Column(type="string", length=255)
     */
    private $pays;

    /**
     * @Assert\NotBlank (message="Ce champs ne peut être vide")
     * @ORM\Column(type="string", length=255)
     */
    private $type;

    /**
     * @ORM\ManyToOne(targetEntity=Missions::class, inversedBy="planque")
     */
    private $missions;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCodePlanque(): ?int
    {
        return $this->code_planque;
    }

    public function setCodePlanque(int $code_planque): self
    {
        $this->code_planque = $code_planque;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getPays(): ?string
    {
        return $this->pays;
    }

    public function setPays(string $pays): self
    {
        $this->pays = $pays;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getMissions(): ?Missions
    {
        return $this->missions;
    }

    public function setMissions(?Missions $missions): self
    {
        $this->missions = $missions;

        return $this;
    }

    const PLANQUETYPE = [
        'Studio' => 'Studio',
        'Maison' => 'Maison',
        'Appartement' => 'Appartement',
        'Hotel' => 'Hotel'
    ];

}

templates/espace/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}Espace Privé{% endblock %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-6">
                <button class="btn btn-light">
                    <a href="{{ path('app_logout') }}" class="nav-link link-danger"> <h2 class="m-auto">Se Deconnecter</h2></a>
                </button>
            </div>
        </div>
    </div>
    <div class="container-md main-title rounded mt-5">
        <div class="d-flex">
            <h1 class="m-auto justify-content-center">Menu de Gestion Principal</h1>
        </div>
    </div>


    <div class="container-fluid row">
        <div class="col-6">
            <div class="container rounded listing mt-5">
                <div class=" text-center" >
                    <h2>Missions</h2>
                </div>
                <table  class="container mt-2">
                    <thead class=" text-center">
                    <tr class="listing_headers">
                        <th>Nom de Code</th>
                        <th>Date Début</th>
                        <th>Date Fin</th>
                        <th>Statut</th>
                        <th>Modifier</th>
                        <th>Supprimer</th>
                    </tr>
                    </thead>
                    <tbody class=" text-center">
                    {% for mission in missions %}
                        <tr class="border-bottom">
                            <td><b><i>{{ mission.nomCode }}</i></b></td>
                            <td>{{ mission.dateDebut|date('d/m/y')}}</td>
                            <td>{{ mission.dateFin|date('d/m/y')}}</td>
                            <td>{{ mission.statut }}</td>
                            <td>
                                <a href="{{ path('mission.edit', {'id': mission.id}) }}" class="btn btn-light m-auto">Modifier</a>
                            </td>
                            <td>
                                <form method="post" action="{{ path('mission.delete', {'id': mission.id}) }}" class="m-auto mt-2">
                                    <input type="hidden" name="_method" value="DELETE">
                                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ mission.id) }}">
                                    <button class="btn btn-danger text-center mb-2">Supprimer</button>
                                </form>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="container-md w-25 mt-4">
                <div class="row p-0 m-0">
                    <button class="btn btn-primary col">
                        <a href="{{ path('mission.create')}}" class="btn"><h2 class="m-auto">Créer Mission</h2></a>
                    </button>
                </div>
            </div>
        </div>



        <div class="col-6">
            <div class="container rounded listing mt-5">
                <div class=" text-center" >
                    <h2>Agents</h2>
                </div>
                <table  class="container mt-2">
                    <thead class=" text-center">
                    <tr class="listing_headers">
                        <th>Nom de Code</th>
                        <th>Prenom</th>
                        <th>Nom</th>
                        <th>Nationalité</th>
                        <th>Specialité</th>
                        <th>Modifier</th>
                        <th>Supprimer</th>
                    </tr>
                    </thead>
                    <tbody class=" text-center">
                    {% for agent in agents %}
                        <tr class="border-bottom">
                            <td><b><i>{{ agent.codeAgent }}</i></b></td>
                            <td>{{ agent.prenom }}</td>
                            <td>{{ agent.nom }}</td>
                            <td>{{ agent.nationalite }}</td>
                            <td>{{ agent.specialite }}</td>

                            <td>
                                <a href="{{ path('agent.edit', {'id': agent.id}) }}" class="btn btn-light m-auto">Modifier</a>
                            </td>
                            <td>
                                 <form method="post" action="{{ path('agent.delete', {'id': agent.id}) }}" class="m-auto mt-2">
                                    <input type="hidden" name="_method" value="DELETE">
                                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ agent.id) }}">
                                    <button class="btn btn-danger text-center mb-2">Supprimer</button>
                                </form>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="container-md w-25 mt-4">
                <div class="row">
                    <button class="btn btn-primary col">
                         <a href="{{ path('agent.create')}}" class="btn m-2"><h2 class="m-auto">Créer Agent</h2></a>
                    </button>
                </div>
            </div>
        </div>
    </div>

    <div class="row container-fluid">
        <div class="col-6">
            <div class="container rounded listing mt-5">
                <div class=" text-center" >
                    <h2>Cibles</h2>
                </div>
                <table  class="container mt-2">
                    <thead class=" text-center">
                    <tr class="listing_headers">
                        <th>Nom de Code</th>
                        <th>Nom</th>
                        <th>Prenom</th>
                        <th>Modifier</th>
                        <th>Supprimer</th>
                    </tr>
                    </thead>
                    <tbody class=" text-center">
                    {% for cible in cibles %}
                        <tr class="border-bottom">
                            <td><b><i> {{ cible.nomCode }} </i></b></td>
                            <td>{{ cible.nom }}</td>
                            <td>{{ cible.prenom}}</td>
                            <td>
                                 <a href="{{ path('cible.edit', {'id': cible.id}) }}" class="btn btn-light m-auto">Modifier</a>
                            </td>
                            <td>
                                 <form method="post" action="{{ path('cible.delete', {'id': cible.id}) }}" class="m-auto mt-2">
                                    <input type="hidden" name="_method" value="DELETE">
                                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ cible.id) }}">
                                    <button class="btn btn-danger text-center mb-2">Supprimer</button>
                                </form>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="container-md w-25 mt-4">
                <div class="row p-0 m-0">
                    <button class="btn btn-primary col">
                        <a href="{{ path('cible.create')}}" class="btn"><h2 class="m-auto">Créer Cible</h2></a>
                    </button>
                </div>
            </div>
        </div>


        <div class="col-6">
            <div class="container rounded listing mt-5">
                <div class=" text-center" >
                    <h2>Contacts</h2>
                </div>
                <table  class="container mt-2">
                    <thead class=" text-center">
                    <tr class="listing_headers">
                        <th>Nom de Code</th>
                        <th>Nom</th>
                        <th>Prenom</th>
                        <th>Modifier</th>
                        <th>Supprimer</th>
                    </tr>
                    </thead>
                    <tbody class=" text-center">
                    {% for contact in contacts %}
                        <tr class="border-bottom">
                            <td><b><i>{{ contact.nomCode }}</i></b></td>
                            <td>{{ contact.nom }}</td>
                            <td>{{ contact.prenom}}</td>
                            <td>
                                 <a href="{{ path('contact.edit', {'id': contact.id}) }}" class="btn btn-light m-auto">Modifier</a>
                            </td>
                            <td>
                                 <form method="post" action="{{ path('contact.delete', {'id': contact.id}) }}" class="m-auto mt-2">
                                    <input type="hidden" name="_method" value="DELETE">
                                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ contact.id) }}">
                                    <button class="btn btn-danger text-center mb-2">Supprimer</button>
                                </form>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="container-md mt-4" style="width: 200px">
                <div class="row p-0 m-0">
                    <button class="btn btn-primary col">
                        <a href="{{ path('contact.create')}}" class="btn w-auto"  ><h2 class="m-auto">Créer Contact</h2></a>
                    </button>
                </div>
            </div>
        </div>
    </div>


    <div class="container-fluid row">
        <div class="col-6">
            <div class="container rounded listing mt-5">
                <div class=" text-center" >
                    <h2>Planques</h2>
                </div>
                <table  class="container mt-2">
                    <thead class=" text-center">
                    <tr class="listing_headers">
                        <th>Code Planque</th>
                        <th>Adresse</th>
                        <th>Pays</th>
                        <th>Type</th>
                        <th>Modifier</th>
                        <th>Supprimer</th>
                    </tr>
                    </thead>
                    <tbody class=" text-center">
                    {% for planque in planques %}
                        <tr class="border-bottom">
                            <td><b>{{ planque.codePlanque }}</i></b></td>
                            <td>{{ planque.adresse }}</td>
                            <td>{{ planque.pays}}</td>
                            <td>{{ planque.type}}</td>
                            <td>
                                <a href="{{ path('planque.edit', {'id': planque.id}) }}" class="btn btn-light m-auto">Modifier</a>
                            </td>
                            <td>
                                <form method="post" action="{{ path('planque.delete', {'id': planque.id}) }}" class="m-auto mt-2">
                                    <input type="hidden" name="_method" value="DELETE">
                                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ planque.id) }}">
                                    <button class="btn btn-danger text-center mb-2">Supprimer</button>
                                </form>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="container-md w-25 mt-4">
                <div class="row p-0 m-0">
                    <button class="btn btn-primary col">
                        <a href="{{ path('planque.create')}}" class="btn"><h2 class="m-auto">Créer Planque</h2></a>
                    </button>
                </div>
            </div>
        </div>
    </div>





{% endblock %}